### ISSUE TITLE
A number of imports are now missing

### ISSUE THREAD

**Issue by phocks** [campvanilla/casualdb#16]
I managed to get this working by cloning the repo and updating the imports to use either older versions or other URLs but I'm just letting you know that it looks like there are a few 404 errors now when trying to import.

eg.

```
error: Import 'https://deno.land/x/lodash@4.17.19/matches.js' failed: 404 Not Found
Imported from "file:///C:/Users/phocks/Sites/rise/lib/CasualDB/operator/collection.ts:1"
```

I changed to `import matches from "https://deno.land/x/lodash@4.17.15-es/matches.js";`

```
error: Uncaught Error: Import 'https://deno.land/std@0.75.0/fs/write_json.ts' failed: 404 Not Found
Imported from "file:///C:/Users/phocks/Sites/rise/lib/CasualDB/writeWorker.ts:1"
```

I changed to: `import { writeJson } from 'https://deno.land/x/jsonfile/mod.ts';`

etc.

**Comment by abinavseelan** [comment]
Hey! Thanks for raising this.

We'll have a look at this over the weekend. But if you have the changes ready for fixing this, please feel free to raise a PR as well. 😄

**Comment by phocks** [comment]
Thanks for this. I'm only just starting out with Deno so not quite confident of doing the fix properly. But I may have time to figure something out. Cheers. Good luck!

**Comment by jackfiszr** [comment]
Hello!
You should always import specific versions of libraries. Otherwise, the newest (and possibly incompatible) version will be imported. I did the PR.
Also, all external imports should be in one file (deps.ts). That would make them easier to maintain.
