### ISSUE TITLE
[Bug] Quick usage example does not run.

### ISSUE THREAD

**Issue by Tezza48** [campvanilla/casualdb#2]
Steps to reproduce.

1. Create a blank `.ts` file.
2. Paste in [_Quick Usage_](https://deno.land/x/casualdb/#quick-usage) code with the correct import statement for CasualDB.
3. Execute the code using `deno run --allow-read --allow-write --unstable .\index.ts`
4. Observe the following error: 
```sh
error: Uncaught Error: Cannot resolve module "file:///D:/source/denoPortfolio/database/writeWorker.ts"
    at WorkerImpl.#poll ($deno$/web/workers.ts:198:17)
```

My source: https://gist.github.com/Tezza48/2618a1d52e894d68e79161afcfa098cf

About me:
I am a web game developer from England at a small studio, working in Typescript. I'm using Deno purely for for learning, currently working on a blog/portfolio.

**Comment by rheaditi** [comment]
Hello @Tezza48!
Thanks for reporting this issue!

The bug seems to be related to denoland/deno#2751 and how Worker imports are being resolved.

Will be fixed in #3 😁

**Comment by Tezza48** [comment]
Cheers!

**Comment by abinavseelan** [comment]
@Tezza48 We've released [v0.1.1](https://github.com/campvanilla/casualdb/releases/tag/0.1.1) for the package.

Can you try installing this version and see if things work fine now? 

```diff
- import { CasualDB } from "https://deno.land/x/casualdb@0.1.0/mod.ts"
+ import { CasualDB } from "https://deno.land/x/casualdb@0.1.1/mod.ts"
```

Also, we've made a deno cli flag mandatory. You'd have to pass `--allow-net` as well.

**Comment by abinavseelan** [comment]
@all-contributors

Add @Tezza48 for bug

**Comment by Tezza48** [comment]
Appears to work like a dream. Thank you very much!
