### ISSUE TITLE
Version v0.1.3 missing from Deno website

### ISSUE THREAD

**Issue by jackfiszr** [campvanilla/casualdb#20]
The new tag did not appear on deno.land/x
Do you have the GitHub hook properly set up?
This might be because of renaming the master branch to main.

**Comment by rheaditi** [comment]
This must be something new.. we didn't have a webhook before (for <0.1.2).
[I recall adding our config directly to the deno website](https://github.com/denoland/deno_website2/pull/763).

Will need to check out how to migrate to the webhook way and/or if some ref needs to be changed somewhere. Would you happen to know about this?

Also, thanks for following up on this @jackfiszr! 😁

**Comment by abinavseelan** [comment]
Hey @jackfiszr 👋 

We got the webhook working! As @rheaditi has mentioned, we didn't have to do anything earlier for a release to get pushed to deno.land. Got the webhook added and now [v0.1.4](https://deno.land/x/casualdb@v0.1.4) is available on deno.land. 🙂 

Thanks for pointing this out!
